---
- name: Install Nginx
  hosts: lxcs
  become: true
  tasks:
    - name: Install nginx package
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
