name: Go CI

on:
  push:
    branches:
      - 'feature/authentification'
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  build-test-go:
    name: Build & Test Go 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4

      - name: Build Go Code
        run: go build ./...
        working-directory: authentification

      - name: Run Tests
        run: go test -v ./...
        working-directory: authentification


  merge-to-main:
    name: Merge Into Main
    runs-on: ubuntu-latest
    needs: build-test-go
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git (Talfaza)
        run: |
          git config --global user.name "Talfaza"
          git config --global user.email "charifyahia4@gmail.com"

      - name: Merge dev into main
        run: |
          git checkout main
          git merge ${{ github.ref_name }} --no-edit
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git main
